#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "Chip8"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_LOAD_ADDRESS 0x200
#define CHIP8_DISPLAY_WIDTH 64
#define CHIP8_DISPLAY_HEIGHT 32
#define CHIP8_WINDOW_SCALER 20
#define CHIP8_NUM_REGISTERS 16
#define CHIP8_STACK_SIZE 16
#define CHIP8_TOTAL_KEYS 16
#define CHIP8_DEFAULT_SPRITE_HEIGHT 5

#endif